name: git push
trigger:
  fileExtension: add.git.txt
cmd:
  exec: |
    cd /Users/art/Dropbox/dev/nodejs/electron/winegold &&
    git add . &&
    git commit -m "{{inside}}" &&
    git push --porcelain
autolaunch: true
