name: git push
trigger:
  fileExtension: add.git.txt
cmd:
  exec: |
    cd ~/Documents/GitHub/winegold/ &&
    git add . &&
    git commit -m "{{inside}}" &&
    git push --porcelain
autolaunch: true
